apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jobset-operator-instance
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/name: jobset-operator-instance
    app.kubernetes.io/part-of: rhoai-distributed
spec:
  project: default
  source:
    repoURL: https://github.com/redhat-ai-americas/rhoai-distributed.git
    targetRevision: main
    path: platform/jobset-operator/instance
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
