apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pipelines-server
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/name: pipelines-server
    app.kubernetes.io/part-of: rhoai-distributed
spec:
  project: default
  source:
    repoURL: https://github.com/redhat-ai-americas/rhoai-distributed.git
    targetRevision: main
    path: platform/pipelines
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 10m
  ignoreDifferences:
    - group: datasciencepipelinesapplications.opendatahub.io
      kind: DataSciencePipelinesApplication
      name: dspa
      jsonPointers:
        - /spec
